### ISSUE TITLE
Filter class refactor?

### ISSUE THREAD

**Issue by jnoellsch** [jnoellsch/ektron-fluentapi#6]
Should the Filter<T> class be refactored to take on the field property as another generic type?

**Comment by ssartell** [comment]
I think you'll need to show me in person.  Are you trying to get rid of the object parameter?  It looks like that's how Ektron takes in filter values anyways.

**Comment by ssartell** [comment]
Just for future reference, this can't be done. ContentCollectionCriteria doesn't inherit from Criteria<ContentCollectionProperty> and implements it's own version of AddFilter instead. Therefore AddFilter can't be called polymorphically.  Maybe there's some way around it where we handle ContentCollectionProperty differently, but it seems difficult at best.
